# Site settings
title: Little World
header-img: img/home-bg.jpg
email: cilendeng@gmail.com
copyright_name: cilendeng
description: "Little world,but if you explore,it can be beautiful"
baseurl: ""
url: "http://littleworld.me"
twitter_username: cilendeng
github_username:  carbin-gun
facebook_username:  cilendeng
email_username:  cilendeng

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
